Afrikpay\SymfonyMessaging\Service\Impl\MailServiceImpl:
  requestDtoClass: Afrikpay\SymfonyMessaging\Dto\Email\EmailCreateDto
  createDtoClass: Afrikpay\SymfonyMessaging\Dto\Email\EmailCreateDto
  entityDtoClass: Afrikpay\SymfonyMessaging\Dto\Email\EmailDto
  apiRequestDtoClass: Afrikpay\SymfonyMessaging\Dto\Email\EmailDto
  apiResponseDtoClass: Afrikpay\SymfonyMessaging\Dto\Email\EmailDto
  responseDtoClass: Afrikpay\SymfonyMessaging\Dto\Email\EmailDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: MAIL_API_ENABLED
  callbackUrl: null
  saveEntity: true
  asyncMode: false
  idleModeAccepted: true
  idleModeParameter: MAIL_IDLE
  cacheEnabled: false
  apiTemplate: null
  apiHeadersTemplate: null
  apiPathVariablesTemplate: null
  apiConfigurationTemplate: null
  apiResponseTemplate: null
  apiCallbackResponseTemplate: null
  regexTemplate: null
  uniqueTemplate: null
  updateTemplate: null
  entityRequired: false
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

Afrikpay\SymfonyMessaging\Service\Impl\SmsSenderFirstChannelServiceImpl:
  requestDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsCreateDto
  createDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsCreateDto
  entityDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsDto
  apiRequestDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsApiRequestDto
  apiResponseDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsApiResponseDto
  responseDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: SMS_API_ENABLED
  callbackUrl: null
  saveEntity: true
  asyncMode: false
  idleModeAccepted: true
  cacheEnabled: false
  idleModeParameter: SMS_IDLE
  apiTemplate: sms-lmt.json
  apiHeadersTemplate: sms-lmt.yaml
  apiPathVariablesTemplate: sms-lmt.yaml
  apiConfigurationTemplate: sms-lmt.yaml
  apiResponseTemplate: sms-lmt.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: sms.yaml
  uniqueTemplate: null
  updateTemplate: null
  entityRequired: false
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

Afrikpay\SymfonyMessaging\Service\Impl\SmsSenderSecondChannelServiceImpl:
  requestDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsCreateDto
  createDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsCreateDto
  entityDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsDto
  apiRequestDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsApiRequestDto
  apiResponseDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsApiResponseDto
  responseDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: SMS_API_ENABLED
  callbackUrl: null
  saveEntity: true
  asyncMode: false
  idleModeAccepted: true
  cacheEnabled: false
  idleModeParameter: SMS_IDLE
  apiTemplate: sms-lmt.json
  apiHeadersTemplate: sms-lmt.yaml
  apiPathVariablesTemplate: sms-lmt.yaml
  apiConfigurationTemplate: sms-lmt.yaml
  apiResponseTemplate: sms-lmt.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: sms.yaml
  uniqueTemplate: null
  updateTemplate: null
  entityRequired: false
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

Afrikpay\SymfonyMessaging\Service\Impl\SmsSenderThirdChannelServiceImpl:
  requestDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsCreateDto
  createDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsCreateDto
  entityDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsDto
  apiRequestDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsApiRequestDto
  apiResponseDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsApiResponseDto
  responseDtoClass: Afrikpay\SymfonyMessaging\Dto\Sms\SmsDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: SMS_API_ENABLED
  callbackUrl: null
  saveEntity: true
  asyncMode: false
  idleModeAccepted: true
  cacheEnabled: false
  idleModeParameter: SMS_IDLE
  apiTemplate: sms-lmt.json
  apiHeadersTemplate: sms-lmt.yaml
  apiPathVariablesTemplate: sms-lmt.yaml
  apiConfigurationTemplate: sms-lmt.yaml
  apiResponseTemplate: sms-lmt.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: sms.yaml
  uniqueTemplate: null
  updateTemplate: null
  entityRequired: false
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

App\Service\Impl\ReferenceAdapterServiceImpl:
  requestDtoClass: App\Dto\Reference\ReferenceCreateDto
  createDtoClass: App\Dto\Reference\ReferenceCreateDto
  entityDtoClass: App\Dto\Reference\ReferenceDto
  apiRequestDtoClass: App\Dto\Reference\ReferenceApiRequestDto
  apiResponseDtoClass: App\Dto\Reference\ReferenceApiResponseDto
  responseDtoClass: App\Dto\Reference\ReferenceDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: REFERENCE_API_ENABLED
  callbackUrl: null
  saveEntity: true
  asyncMode: false
  idleModeAccepted: true
  cacheEnabled: true
  idleModeParameter: REF_IDLE
  apiTemplate: reference.txt
  apiHeadersTemplate: reference.yaml
  apiPathVariablesTemplate: reference.yaml
  apiConfigurationTemplate: reference.yaml
  apiResponseTemplate: reference.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: reference.yaml
  uniqueTemplate: reference.yaml
  updateTemplate: null
  entityRequired: false
  authUsernameParameter: API_USERNAME_TOKEN
  authPasswordParameter: API_PASSWORD_TOKEN
  authPinParameter: null
  statusUpdate: true
  acceptFinalStatus: true
  statusMode: false
  debugRequest: false
  debugResponse: false

App\Service\Impl\ReferenceNoCacheAdapterServiceImpl:
  requestDtoClass: App\Dto\Reference\ReferenceCreateDto
  createDtoClass: App\Dto\Reference\ReferenceCreateDto
  entityDtoClass: App\Dto\Reference\ReferenceDto
  apiRequestDtoClass: App\Dto\Reference\ReferenceApiRequestDto
  apiResponseDtoClass: App\Dto\Reference\ReferenceApiResponseDto
  responseDtoClass: App\Dto\Reference\ReferenceDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: REFERENCE_API_ENABLED
  callbackUrl: null
  saveEntity: false
  asyncMode: false
  idleModeAccepted: true
  cacheEnabled: false
  idleModeParameter: REF_IDLE
  apiTemplate: reference.xml
  apiHeadersTemplate: reference.yaml
  apiPathVariablesTemplate: reference.yaml
  apiConfigurationTemplate: reference.yaml
  apiResponseTemplate: reference.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: reference.yaml
  uniqueTemplate: null
  updateTemplate: null
  entityRequired: false
  authUsernameParameter: API_USERNAME_TOKEN
  authPasswordParameter: API_PASSWORD_TOKEN
  authPinParameter: null
  statusUpdate: true
  acceptFinalStatus: true
  statusMode: true
  debugRequest: false
  debugResponse: false

App\Service\Impl\PaymentAdapterServiceImpl:
  requestDtoClass: App\Dto\Transaction\TransactionRequestDto
  createDtoClass: App\Dto\Transaction\TransactionCreateDto
  entityDtoClass: App\Dto\Transaction\PaymentTransactionDto
  apiRequestDtoClass: App\Dto\Transaction\TransactionApiRequestDto
  apiResponseDtoClass: App\Dto\Transaction\TransactionApiResponseDto
  responseDtoClass: App\Dto\Transaction\PaymentTransactionDto
  callbackDtoClass: App\Dto\Transaction\TransactionCallbackDto
  authorizeParameter: TRANSACTION_API_ENABLED
  callbackUrl: null
  saveEntity: true
  asyncMode: false
  idleModeAccepted: false
  cacheEnabled: true
  idleModeParameter: PAYMENT_IDLE
  apiTemplate: payment-transaction.json
  apiHeadersTemplate: payment-transaction.yaml
  apiPathVariablesTemplate: null
  apiConfigurationTemplate: payment-transaction.yaml
  apiResponseTemplate: payment-transaction.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: payment-transaction.yaml
  uniqueTemplate: payment-transaction.yaml
  updateTemplate: null
  entityRequired: false
  authUsernameParameter: "{user.username}"
  authPasswordParameter: "{user.password}"
  authPinParameter: confirmationPassword
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

App\Service\Impl\TransactionAdapterServiceImpl:
  requestDtoClass: App\Dto\Transaction\TransactionCreateDto
  createDtoClass: App\Dto\Transaction\TransactionCreateDto
  entityDtoClass: App\Dto\Transaction\TransactionDto
  apiRequestDtoClass: App\Dto\Transaction\TransactionApiRequestDto
  apiResponseDtoClass: App\Dto\Transaction\TransactionApiResponseDto
  responseDtoClass: App\Dto\Transaction\TransactionDto
  callbackDtoClass: App\Dto\Transaction\TransactionCallbackDto
  authorizeParameter: TRANSACTION_API_ENABLED
  callbackUrl: null
  saveEntity: false
  asyncMode: false
  idleModeAccepted: false
  cacheEnabled: true
  idleModeParameter: TRX_IDLE
  apiTemplate: transaction.json
  apiHeadersTemplate: transaction.yaml
  apiPathVariablesTemplate: null
  apiConfigurationTemplate: transaction.yaml
  apiResponseTemplate: transaction.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: transaction.yaml
  uniqueTemplate: transaction.yaml
  updateTemplate: transaction.yaml
  entityRequired: true
  authUsernameParameter: API_USERNAME_TOKEN
  authPasswordParameter: API_PASSWORD_TOKEN
  authPinParameter: null
  statusUpdate: false
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

App\Service\Impl\TransactionRollbackAdapterServiceImpl:
  requestDtoClass: App\Dto\Transaction\TransactionFinancialIdDto
  createDtoClass: App\Dto\Transaction\TransactionCreateDto
  entityDtoClass: App\Dto\Transaction\RollbackTransactionDto
  apiRequestDtoClass: App\Dto\Transaction\TransactionApiRequestDto
  apiResponseDtoClass: App\Dto\Transaction\TransactionApiResponseDto
  responseDtoClass: App\Dto\Transaction\RollbackTransactionDto
  callbackDtoClass: App\Dto\Transaction\TransactionCallbackDto
  authorizeParameter: TRANSACTION_API_ENABLED
  callbackUrl: null
  saveEntity: false
  asyncMode: false
  idleModeAccepted: false
  cacheEnabled: true
  idleModeParameter: PAYMENT_IDLE
  apiTemplate: null
  apiHeadersTemplate: rollback-transaction.yaml
  apiPathVariablesTemplate: rollback-transaction.yaml
  apiConfigurationTemplate: rollback-transaction.yaml
  apiResponseTemplate: rollback-transaction.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: rollback-transaction.yaml
  uniqueTemplate: rollback-transaction.yaml
  updateTemplate: null
  entityRequired: true
  authUsernameParameter: ACCOUNT_ADMIN_API_USERNAME
  authPasswordParameter: ACCOUNT_ADMIN_API_PASSWORD
  authPinParameter: null
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

App\Service\Impl\TransactionCommissionAdapterServiceImpl:
  requestDtoClass: App\Dto\Transaction\TransactionFinancialIdDto
  createDtoClass: App\Dto\Transaction\TransactionCreateDto
  entityDtoClass: App\Dto\Transaction\CommissionTransactionDto
  apiRequestDtoClass: App\Dto\Transaction\TransactionApiRequestDto
  apiResponseDtoClass: App\Dto\Transaction\TransactionApiResponseDto
  responseDtoClass: App\Dto\Transaction\CommissionTransactionDto
  callbackDtoClass: App\Dto\Transaction\TransactionCallbackDto
  authorizeParameter: TRANSACTION_API_ENABLED
  callbackUrl: null
  saveEntity: false
  asyncMode: false
  idleModeAccepted: false
  cacheEnabled: true
  idleModeParameter: PAYMENT_IDLE
  apiTemplate: commission-transaction.json
  apiHeadersTemplate: commission-transaction.yaml
  apiPathVariablesTemplate: null
  apiConfigurationTemplate: commission-transaction.yaml
  apiResponseTemplate: commission-transaction.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: commission-transaction.yaml
  uniqueTemplate: commission-transaction.yaml
  updateTemplate: null
  entityRequired: true
  authUsernameParameter: ACCOUNT_ADMIN_API_USERNAME
  authPasswordParameter: ACCOUNT_ADMIN_API_PASSWORD
  authPinParameter: null
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

App\Service\Impl\StatusAdapterServiceImpl:
  requestDtoClass: App\Dto\Transaction\TransactionFindDto
  createDtoClass: App\Dto\Transaction\TransactionFindDto
  entityDtoClass: App\Dto\Transaction\TransactionDto
  apiRequestDtoClass: App\Dto\Transaction\TransactionApiRequestDto
  apiResponseDtoClass: App\Dto\Transaction\TransactionApiResponseDto
  responseDtoClass: App\Dto\Transaction\TransactionDto
  callbackDtoClass: App\Dto\Transaction\TransactionCallbackDto
  authorizeParameter: STATUS_API_ENABLED
  callbackUrl: null
  saveEntity: false
  asyncMode: false
  idleModeAccepted: false
  cacheEnabled: true
  idleModeParameter: STATUS_IDLE
  apiTemplate: status.json
  apiHeadersTemplate: status.yaml
  apiPathVariablesTemplate: status.yaml
  apiConfigurationTemplate: status.yaml
  apiResponseTemplate: status.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: status.yaml
  uniqueTemplate: status.yaml
  updateTemplate: null
  entityRequired: true
  authUsernameParameter: API_USERNAME_TOKEN
  authPasswordParameter: API_PASSWORD_TOKEN
  authPinParameter: null
  statusUpdate: true
  acceptFinalStatus: true
  statusMode: true
  debugRequest: false
  debugResponse: false

Afrikpay\SymfonyAdapter\Service\Impl\TokenAdapterServiceImpl:
  requestDtoClass: Afrikpay\SymfonyAdapter\Dto\Token\TokenCreateDto
  createDtoClass: Afrikpay\SymfonyAdapter\Dto\Token\TokenCreateDto
  entityDtoClass: Afrikpay\SymfonyAdapter\Dto\Token\TokenDto
  apiRequestDtoClass: Afrikpay\SymfonyAdapter\Dto\Token\TokenApiRequestDto
  apiResponseDtoClass: Afrikpay\SymfonyAdapter\Dto\Token\TokenApiResponseDto
  responseDtoClass: Afrikpay\SymfonyAdapter\Dto\Token\TokenDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: TOKEN_API_ENABLED
  callbackUrl: null
  saveEntity: false
  asyncMode: false
  idleModeAccepted: false
  cacheEnabled: true
  idleModeParameter: TOKEN_IDLE
  apiTemplate: token.json
  apiHeadersTemplate: token.yaml
  apiPathVariablesTemplate: token.yaml
  apiConfigurationTemplate: token.yaml
  apiResponseTemplate: token.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: token.yaml
  uniqueTemplate: null
  updateTemplate: null
  entityRequired: false
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

Afrikpay\SymfonySecurity\Service\Impl\AccountAdapterServiceImpl:
  requestDtoClass: Afrikpay\SymfonySecurity\Dto\Account\AccountCreateDto
  createDtoClass: Afrikpay\SymfonySecurity\Dto\Account\AccountCreateDto
  entityDtoClass: Afrikpay\SymfonySecurity\Dto\Account\AccountDto
  apiRequestDtoClass: Afrikpay\SymfonySecurity\Dto\Account\AccountDto
  apiResponseDtoClass: Afrikpay\SymfonySecurity\Dto\Account\AccountDto
  responseDtoClass: Afrikpay\SymfonySecurity\Dto\Account\AccountDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: ACCOUNT_API_ENABLED
  callbackUrl: null
  saveEntity: false
  asyncMode: false
  idleModeAccepted: false
  cacheEnabled: true
  idleModeParameter: ACCOUNT_IDLE
  apiTemplate: null
  apiHeadersTemplate: account.yaml
  apiPathVariablesTemplate: account.yaml
  apiConfigurationTemplate: account.yaml
  apiResponseTemplate: account.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: account.yaml
  uniqueTemplate: null
  updateTemplate: null
  entityRequired: false
  authUsernameParameter: ACCOUNT_ADMIN_API_USERNAME
  authPasswordParameter: ACCOUNT_ADMIN_API_PASSWORD
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false

Afrikpay\SymfonyThirdpartyAdapter\Service\Impl\FeesAdapterServiceImpl:
  requestDtoClass: Afrikpay\SymfonyThirdpartyAdapter\Dto\Fees\FeesCreateDto
  createDtoClass: Afrikpay\SymfonyThirdpartyAdapter\Dto\Fees\FeesCreateDto
  entityDtoClass: Afrikpay\SymfonyThirdpartyAdapter\Dto\Fees\FeesDto
  apiRequestDtoClass: Afrikpay\SymfonyThirdpartyAdapter\Dto\Fees\FeesApiRequestDto
  apiResponseDtoClass: Afrikpay\SymfonyThirdpartyAdapter\Dto\Fees\FeesApiResponseDto
  responseDtoClass: Afrikpay\SymfonyThirdpartyAdapter\Dto\Fees\FeesDto
  callbackDtoClass: Afrikpay\SymfonyUtilities\Model\BaseObject
  authorizeParameter: FEES_API_ENABLED
  callbackUrl: null
  saveEntity: false
  asyncMode: false
  idleModeAccepted: false
  cacheEnabled: true
  idleModeParameter: FEES_IDLE
  apiTemplate: fees.txt
  apiHeadersTemplate: fees.yaml
  apiPathVariablesTemplate: fees.yaml
  apiConfigurationTemplate: fees.yaml
  apiResponseTemplate: fees.yaml
  apiCallbackResponseTemplate: null
  regexTemplate: fees.yaml
  uniqueTemplate: null
  updateTemplate: null
  entityRequired: false
  authUsernameParameter: null
  authPasswordParameter: null
  statusUpdate: true
  acceptFinalStatus: false
  statusMode: false
  debugRequest: false
  debugResponse: false
