apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: airtime-mtn
build:
  tagPolicy:
    envTemplate:
      template: "{{.ENV}}"
  artifacts:
  - image: gcr.io/bootstrap-cicd-060623/airtime-mtn
  googleCloudBuild:
    projectId: bootstrap-cicd-060623
profiles:
- name: qa
  activation:
    - env: ENV=qa
  manifests:
    kustomize:
      paths: 
      - overlay/
deploy:
  cloudrun:
    projectid: prod-app-base-060623
    region: europe-west4
