apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: airtime-mtn
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/secrets: prod-app-base-060623-prod-app-base-060623-pgsql-airtime_mtn_cr_qa-password:projects/prod-secret-060623/secrets/prod-app-base-060623-prod-app-base-060623-pgsql-airtime_mtn_cr_qa-password
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - image: gcr.io/bootstrap-cicd-060623/airtime-mtn:latest-qa
        ports:
        - name: http1
          containerPort: 80
        env:
        - name: DB_USER
          value: airtime_mtn_qa_user
        - name: DB_airtime-mtn
          value: DATABASE_airtime-mtn
        - name: DB_HOST
          value: 172.16.10.2
        - name: GITHUB_KEY
          value: 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
        - name: DB_CONNECTION
          value: prod-app-base-060623:europe-west4:prod-app-base-pgsql-060623
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: prod-app-base-060623-prod-app-base-060623-pgsql-airtime_mtn_cr_qa-password
        resources:
          limits:
            cpu: 2000m
            memory: 4000Mi
