apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: gcr.io/bootstrap-cicd-060623/NAME
  newName: gcr.io/bootstrap-cicd-060623/NAME
  newTag: latest-ENVIRONMENT
nameSuffix: -ENVIRONMENT
patchesStrategicMerge:
- deploy.yaml
