apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
images:
- name: gcr.io/bootstrap-cicd-060623/airtime-mtn
  newName: gcr.io/bootstrap-cicd-060623/airtime-mtn
  newTag: latest-qa
nameSuffix: -qa
patchesStrategicMerge:
- deploy.yaml
